### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by yiedw** [subsquid/subsquid-network-contracts#13] opened 2023-09-05 07:01 UTC
After updating and it was working fine, but since yesterday, there have been no logs after this.  
(all log is subsquid-worker-1 )

{"time": 1693834583755, "level": "INFO", "ns": "etha.worker.state.folder", "msg": "deleting chunk s3://moonbeam-mainnet/0002720101/0004031655-0004045270-8304ceb8 at /app/data/worker/czM6Ly9tb29uYmVhbS1tYWlubmV0"}
{"time": 1693834583755, "level": "INFO", "ns": "etha.worker.state.folder", "msg": "deleting chunk s3://moonbeam-mainnet/0002720101/0004045271-0004057097-afd61176 at /app/data/worker/czM6Ly9tb29uYmVhbS1tYWlubmV0"}
{"time": 1693834583756, "level": "INFO", "ns": "etha.worker.state.folder", "msg": "deleting chunk s3://moonbeam-mainnet/0002720101/0004057098-0004069167-8ba9fc70 at /app/data/worker/czM6Ly9tb29uYmVhbS1tYWlubmV0"}
{"time": 1693834583757, "level": "INFO", "ns": "etha.worker.state.folder", "msg": "deleting chunk s3://moonbeam-mainnet/0002720101/0004069168-0004080929-a32833df at /app/data/worker/czM6Ly9tb29uYmVhbS1tYWlubmV0"}
{"time": 1693834583757, "level": "INFO", "ns": "etha.worker.state.folder", "msg": "deleting chunk s3://moonbeam-mainnet/0002720101/0004080930-0004092835-d0e9749a at /app/data/worker/czM6Ly9tb29uYmVhbS1tYWlubmV0"}
{"time": 1693834583758, "level": "INFO", "ns": "etha.worker.state.folder", "msg": "deleting chunk s3://moonbeam-mainnet/0002720101/0004092836-0004103617-535f60e4 at /app/data/worker/czM6Ly9tb29uYmVhbS1tYWlubmV0"}
{"time": 1693834583758, "level": "INFO", "ns": "etha.worker.state.sync_proc", "msg": "update task finished"}

When I restarted, I started getting this error.

{"time": 1693896596442, "level": "ERROR", "ns": "etha.worker.p2p.server", "msg": "terminating program due to SIGTERM"}
{"time": 1693896600565, "level": "INFO", "ns": "etha.worker.p2p.server", "msg": "Local peer ID: 12D3KooWMJcccv5jRnqLqs1rQkWZUfoWz6XgH4dKFHZVXk8RKXfd"}
{"time": 1693896606502, "level": "CRITICAL", "ns": "etha.worker.p2p.server", "msg": "program crashed", "err": "Traceback (most recent call last):\n  File \"/app/env/lib/python3.11/site-packages/etha/util/asyncio.py\", line 84, in run_async_program\n    asyncio.run(run())\n  File \"/usr/local/lib/python3.11/asyncio/runners.py\", line 190, in run\n    return runner.run(main)\n           ^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/runners.py\", line 118, in run\n    return self._loop.run_until_complete(task)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/asyncio/base_events.py\", line 653, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/app/env/lib/python3.11/site-packages/etha/util/asyncio.py\", line 81, in run\n    await program\n  File \"/app/env/lib/python3.11/site-packages/etha/worker/p2p/server.py\", line 286, in _main\n    await monitor_service_tasks([\n  File \"/app/env/lib/python3.11/site-packages/etha/util/asyncio.py\", line 35, in monitor_service_tasks\n    raise exception\n  File \"/app/env/lib/python3.11/site-packages/etha/worker/p2p/server.py\", line 91, in run\n    await monitor_service_tasks([receive_task], log=LOG)\n  File \"/app/env/lib/python3.11/site-packages/etha/util/asyncio.py\", line 35, in monitor_service_tasks\n    raise exception\n  File \"/app/env/lib/python3.11/site-packages/etha/worker/p2p/server.py\", line 94, in _receive_loop\n    async for msg in self._transport.GetMessages(Empty()):\n  File \"/app/env/lib/python3.11/site-packages/grpc/aio/_call.py\", line 326, in _fetch_stream_responses\n    await self._raise_for_status()\n  File \"/app/env/lib/python3.11/site-packages/grpc/aio/_call.py\", line 236, in _raise_for_status\n    raise _create_rpc_error(await self.initial_metadata(), await\ngrpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = \"Socket closed\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer ipv4:172.18.0.2:50051 {grpc_message:\"Socket closed\", grpc_status:14, created_time:\"2023-09-05T06:50:06.476366991+00:00\"}\"\n>"}

it is ubuntu 22.04 and 8 vCpu, 30 ram

**Comment by Wiezzel** [comment] 2023-09-06 09:27
Seemed to be caused by the `p2p-worker`'s inability to connect to the `rpc-node`. Fixed by reinstalling.

**Closed by Wiezzel** 2023-09-06 09:27 UTC
